[atl]
name = "ATL"
desc = "Active Template Library"
more = "A set of template-based C++ classes developed by Microsoft, intended to simplify the programming of Component Object Model (COM) objects"

[apm]
name = "APM"
desc = "Advanced Power Management"
more = "It was developed by Microsoft and Intel around 1992, as a way to provide power management on Intel PCs"
