[clr]
name = "CLR"
desc = "Common Language Runtime"
more = """It's the virtual machine component of Microsoft .NET Framework, manages the execution of .NET programs. 
  
  The CLR provides additional services including memory management, type safety, exception handling, garbage collection, security and thread management. All programs written for the .NET Framework, regardless of programming language, are executed in the CLR. """

[cli]
name = "CLI"
desc = "Common Language Infrastructure"
more = """An open specification and technical standard originally developed by Microsoft and standardized by ISO/IEC (ISO/IEC 23271) and Ecma International (ECMA 335) that describes executable code and a runtime environment that allows multiple high-level languages to be used on different computer platforms without being rewritten for specific architectures. 

  This implies it is platform agnostic. The .NET Framework, .NET and Mono are implementations of the CLI. The metadata format is also used to specify the API definitions exposed by the Windows Runtime."""

[cls]
name = "CLS"
desc = "Common Language Specification"

[cil]
name = "CIL"
desc = "Common Intermediate Language"
more = """The intermediate language binary instruction set defined within the Common Language Infrastructure (CLI) specification

  CIL instructions are executed by a CLI-compatible runtime environment such as the Common Language Runtime. Languages which target the CLI compile to CIL. CIL is object-oriented, stack-based bytecode. Runtimes typically just-in-time compile CIL instructions into native code.

"""

#####################################################

[cpl]
name = "cpl"
desc = "Control PaneL"
more = "Control panel tools for Windows"

[cim]
name = "CIM"
desc = "Common Information Model for PowerShell"

[com]
name = "COM"
desc = "Component Object Model"
more = "A binary-interface standard for software components introduced by Microsoft in 1993. It is used to enable inter-process communication object creation in a large range of programming languages"

[com.DOS]
name = ".COM file"
desc = "command"
more = "A type of simple executable file, the original binary executable format used in CP/M as well as DOS."

[commdlg.Header]
name = "commdlg.h"
more = "Header file for the Common Dialog APIs"
see = 'dlgs.h'

[cderr.Header]
name = "cderr.h"
more = "Header file for Common dialog error return codes"
