[dll]
name = "DLL"
desc = "Dynamic Link Library"

[dia]
name = "DIA SDK"
desc = "Microsoft Debug Interface Access Software Development Kit"
more = "Using DIA API, you can develop applications that search for and browse debug information stored in a .pdb file. Such applications could, for example, report stack trace-back information and analyze performance data."
see = ["pdb"]

[ddk]
name = "DDK"
desc = "Windows Driver Development Kit"

[dlgs.Header]
name = "dlgs.h"
more = "Header file for UI dialog"
see = 'commdlg'

[dde.Header]
name = "dde.h"
more = "Header file for Dynamic Data Exchange structures and definitions"

[dmg]
name = ".dmg"
desc = "Apple Disk Image"
more = "A disk image format commonly used by the macOS operating system. When opened, an Apple Disk Image is mounted as a volume within the Finder."

[dos]
name = "DOS"
desc = "Disk Operating System"
more = "later became a common shorthand for disk-based operating systems on IBM PC compatibles"

[dr-dos]
name = "DR-DOS"
desc = "Digital Research DOS"
more = "Initial release in 1988, latest release in 2011."
