[msdn]
name = "MSDN"
desc = "Microsoft Developer Network"

[masm]
name = "MASM"
desc = "Microsoft Macro Assembler"

[msil]
name = "MSIL"
desc = "Microsoft Intermediate Language"
more = "Deprecated. The bytecode is now officially known as CIL"
see = 'CIL'

[mfc]
name = "MFC"
desc = "Microsoft Foundation Class Library"

[maui]
name = ".NET MAUI"
desc = ".NET Multi-platform App UI"

[msvcrt]
name = "MSVCRT"
desc = "Microsoft Visual C++ Runtime"

[msvc]
name = "MSVC"
desc = "Microsoft Visual C++"
more = "A compiler for the C, C++ and C++/CX programming languages by Microsoft"

[msix.Extension]
name = "MSIX"
desc = "Microsoft appinstaller"

[mmsystem.Header]
name = "mmsystem.h"
more = "Header file for the Multimedia API"

[mmc]
name = "MMC"
desc = "Microsoft Management Console"

[msc]
name = ".msc file"
desc = "Microsoft Management Console programs"
more = "snap-in control files that are associated with the Microsoft Management Console on Windows machines to run administrative tasks."
see = 'MMC'

[mbasic]
name = "MBASIC"
desc = "Microsoft BASIC"
more = "Implementation of BASIC for the CP/M operating system. MBASIC is a descendant of the original Altair BASIC interpreters that were among Microsoft's first products. "