[uac]
name = "UAC"
desc = "User Account Control"
more = "A mandatory access control enforcement feature introduced with Microsoft's Windows Vista and Windows Server 2008. It aims to improve the security of Microsoft Windows by limiting application software to standard user privileges until an administrator authorises an increase or elevation. "
