[uac]
name = "UAC"
desc = "User Account Control"
more = "A mandatory access control enforcement feature introduced with Microsoft's Windows Vista and Windows Server 2008. It aims to improve the security of Microsoft Windows by limiting application software to standard user privileges until an administrator authorises an increase or elevation. "

[unc]
name = "UNC"
desc = "Universal Naming Convention"
more = "The naming system applied in Microsoft Windows. It makes use of double slashes or backslashes to precede the name of the computer. The paths (disks and directories) within the computer are separated with a single slash or backslash (\\)."

[uwp]
name = "UWP"
desc = "Universal Windows Platform"

[usn]
name = "NTFS USN"
desc = "Update Sequence Number change journal"
more = """The USN change journal provides a persistent log of all changes made to files on the volume. As files, directories, and other NTFS objects are added, deleted, and modified, NTFS enters records into the USN change journal, one for each volume on the computer. Each record indicates the type of change and the object changed. New records are appended to the end of the stream.

  See: https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/fsutil-usn
"""
