[vb]
name = "VB"
desc = "Microsoft Visual Basic"
see = ['VC']

[vba]
name = "VBA"
desc = "Visual Basic for Applications"

[vc]
name = "VC"
same = 'MSVC=>msvc'

[vcrt]
same = "MSVCRT=>msvcrt"

[vfat]
name = "VFAT"
desc = "Virtual FAT"

[vdisk]
name = "VDISK"
desc = "virtual disc, i.e. RAM Drive"
