[wow64]
name = "WoW64"
desc = "Windows 32-bit on Windows 64-bit"
more = "A subsystem of the Windows operating system capable of running 32-bit applications on 64-bit Windows. It is included in all 64-bit versions of Windows"

[wpf]
name = "WPF"
desc = "Windows Presentation Foundation"

[winrt]
name = "WinRT"
desc = "Windows Runtime"

[wmi]
name = "WMI"
desc = "Windows Management Instrumentation"
more = "it's deprecated, use CIM instead"
see = ['CIM']

[wsl]
name = "WSL"
desc = "Windows Subsystem for Linux"
see = 'WSA'

[wsa]
name = "WSA"
desc = "Windows Subsystem for Android"
see = 'WSL'

[winpe]
name = "WinPE"
desc = "Windows Preinstallation Environment"
more = "A lightweight version of Windows used for the deployment of PCs, workstations, and servers, or troubleshooting an operating system while it is offline. "


#########################
#        Headers
#########################

[winnls.Header]
name = "winnls.h"
more = "Header file for Internationalization for Windows Applications. See: https://learn.microsoft.com/en-us/windows/win32/api/winnls/"

[wincon.Header]
name = "wincon.h"
more = "Header file for the NT console subsystem"

[winperf.Header]
name = "winperf.h"
more = "Header file for the Performance Monitor data"

[winsvc.Header]
name = "winsvc.h"
more = "Header file for the Service Control Manager"

[windef.Header]
name = "windef.h"
more = "Header file for Basic Windows Type Definitions"
